CC=gcc
OBJCOPY=objcopy

# https://github.com/smonson78/smonson-libtos
LIB_COMPAT=libtos-compat

STD_CFLAGS=-fno-builtin -Wno-format -I. -I$(LIB_COMPAT)
CFLAGS=-O2 -g -Wall $(STD_CFLAGS) -DTOS_COMPAT

LDLIBS=-lc $(LIB_COMPAT)/atari-compat.a -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_gfx -lm -lpthread
LDFLAGS=-nostdlib -L..

TARGET=avecta

OBJS=start.o globals.o gemdefs.o \
	actmon.o animate.o attack.o blt.o caux.o cinput.o \
	damage.o dist.o dorep.o explode.o fileio.o fireball.o \
	instring.o intell.o off.o mouse_on.o mouse_off.o rumdraw.o \
	sell.o startaux.o storsc.o stun.o switchru.o \
	tacmode.o text.o textbig.o texwin.o timetrol.o title.o toggle.o \
	torches.o trapaux.o trapres.o trigtrol.o vbl.o words.o \
	f0.o f1.o f2.o f3.o f4.o f5.o f6.o f7.o f8.o \
	f9.o f10.o f11.o f12.o f13.o f14.o f15.o f16.o \
	debug.o

all: $(TARGET)

$(TARGET): $(TARGET)-shim.elf $(LIB_COMPAT)/atari-compat.a 
	$(CC) -o $(TARGET) $^ $(LDLIBS)

$(TARGET)-combined.elf: $(OBJS)
	$(LD) -o $@ -r $^

$(TARGET)-shim.elf: $(TARGET)-combined.elf
	$(OBJCOPY) --redefine-sym main=compat_main --redefine-sym printf=compat_printf \
	--redefine-sym vfprintf=compat_vfprintf --redefine-sym sprintf=compat_sprintf $^ $@ 

clean:
	$(RM) $(TARGET) *.o *.elf
	$(RM) *~
